#!/bin/sh

set -e

LOG="logger -t pam_mount"

MNTPT=$1;shift
USER=$1;shift
MORRALLA=$*

#if ! mountpoint -q ${MNTPT}; then
#	${LOG} "${MNTPT} is not mounted. Nothing to do..."
#	exit 0
#fi

${LOG} "[${USER}] waiting 10 seconds to logout..."
sleep 10; ## Arreglo chungo para al KDM le de tiempo a tocar el .Xauthority antes de desmontar.

#umount /bin/sigaumount  %(MNTPT) %(USER)

GROUP=`echo ${MNTPT} | cut -d "/" -f 3` 
${LOG} "[${USER}] umounting resources"

for DIR in ${MNTPT}/Documentos ${MNTPT}/Escritorio ${MNTPT} /tmp/${USER}-remote; do
#	if mountpoint -q ${DIR}; then
		umount -lf ${DIR} || ${LOG} "[${USER}] WARNING: Couldn't umount ${DIR}"
#	fi
done

## Avoid to delete important empty directories
touch /home/.directory /root/.directory || true

#if [ ${GROUP} != "local" ]; then
#	TMPDIR=/tmp/${GROUP}/${USER}
#	if [ -d ${TMPDIR} ]; then
#		umount -lf ${TMPDIR}
#		rmdir --parents ${TMPDIR}
#	fi
#fi

rmdir --parents ${MNTPT} --ignore-fail-on-non-empty
${LOG} "[${USER}] Success."
