#!/bin/sh

set -e

if test "$#" -lt 2; then
	cat << EOF
Usage: $0 <user> <mntpt> -o <OPTIONS>

Mount the remote target of an owner name to a local directory.
EOF
	exit 1
fi

LOG="logger -t pam_mount"


OWNER=$1;shift
MNTPT=$1;shift
OWNERUID=$(echo $* | sed 's/.*uid=\([^,]\).*/\1/')
OWNERGID=$(echo $* | sed 's/.*gid=\([^,]\).*/\1/')
OPTIONS=$(echo $* | sed 's/ *-o *//g')

if grep -q "^${OWNER}:.*:${MNTPT}:.*" /etc/passwd; then
	# Warning: this overlaps first domain uids.
	${LOG} "[${OWNER}] local user exists. Nothing to mount"
	exit 0
fi

if mountpoint -q ${MNTPT}; then
	${LOG} "[${OWNER}] mountpoint ${MNTPT} already mounted. Skipping."
	exit 0
fi

${LOG} "[${OWNER}] creating directory structure of mountpoint"
mkdir -p ${MNTPT}

FULLPATH=""
for DIR in $(echo $MNTPT | tr "/" " "); do
	FULLPATH="${FULLPATH}/${DIR}"
	if [ -d ${FULLPATH} ] && [ ${FULLPATH} != "/tmp" ]; then
		# FULLPATH must be created by pam_mount
		chown root:root ${FULLPATH}
		chmod 0751 ${FULLPATH}
	fi
done

# The mountpoint only must be accesible by the user
if [ -d ${MNTPT} ] && [ ${MNTPT} != "/tmp" ]; then
	chmod 0700 ${MNTPT}
	if [ -n "${OWNERUID}" ] && [ -n "${OWNERGID}" ]; then
		chown ${OWNERUID}:${OWNERGID} ${MNTPT}
	fi
fi

GROUP=`echo ${MNTPT} | cut -d "/" -f 3` 

case ${GROUP} in
	${OWNER})
		mount -t tmpfs -o size=20M,mode=0777 tmpfs ${MNTPT}
		exit $?
		;;
	tmp|temp|temporal)
		## Temporal space for local client accounts
		mount -t tmpfs -o size=200M,mode=0777 tmpfs ${MNTPT}
		exit $?
		;;
	local)
		URI="//server/${OWNER}"
		;;
	alumnado.ull.es)
		URI="//aluhome.stic.ull.es/${OWNER}"
		;;
	ull.es)
		URI="//ddv.ull.es/${OWNER}"
		MNTPT=$(echo $MNTPT | sed 's|/home$||')
		;;
	siga*.stic.ull.es)
		URI="//${GROUP}/${OWNER}"
		REMOTE=true
		;;
	*)
		URI="//${GROUP}.aulas.ull.es/${OWNER}"
		;;
esac


${LOG} "[${OWNER}@${URI}] mounting resource to ${MNTPT}"

# Check if FSCache is available in kernel
if egrep -q "^ *CONFIG_CIFS_FSCACHE=y" /boot/config-`uname -r` && \
 ( egrep -q "^ *CONFIG_FSCACHE=y" /boot/config-`uname -r` || \
 ( egrep -q "^ *CONFIG_FSCACHE=m" /boot/config-`uname -r` && lsmod | grep -q fscache ) ); then
	OPTIONS="fsc,${OPTIONS}"
fi

if [ -n "${REMOTE}" ]; then
		REMOTE_DIR=/tmp/${OWNER}-remote
		LOCAL_DIR=/tmp/${OWNER}-local
		WORK_DIR=/tmp/${OWNER}-work
		DESKTOP_DIR=Escritorio
		DOCUMENTS_DIR=Documentos
		mkdir -p   ${LOCAL_DIR} ${REMOTE_DIR} ${WORK_DIR}
		chmod 0700 ${LOCAL_DIR} ${REMOTE_DIR} ${WORK_DIR}

		if ! mount -t cifs ${URI} ${REMOTE_DIR} -o "${OPTIONS}"; then
			${LOG} "[${OWNER}@${URI}] can't mount resource. Mounting on tmpfs"
			mount -t tmpfs -o size=200M,mode=0777 tmpfs ${MNTPT}
			exit 1
		fi

		# check if remote directories exists before bind
		for DIR in ${DESKTOP_DIR} ${DOCUMENTS_DIR}; do	
			if [ -e ${REMOTE_DIR}/private/${DIR} ] && [ ! -d ${REMOTE_DIR}/private/${DIR} ]; then
				mv ${REMOTE_DIR}/private/${DIR} ${LOCAL_DIR}
			fi
			mkdir -p ${REMOTE_DIR}/private/${DIR} ${LOCAL_DIR}/${DIR}
			chown ${OWNERID}:${OWNERGID} ${REMOTE_DIR}/private/${DIR} ${LOCAL_DIR}/${DIR}
			if [ -e ${LOCAL_DIR}/${DIR} ] && [ ! -d ${LOCAL_DIR}/${DIR} ]; then
				mv ${LOCAL_DIR}/${DIR} ${REMOTE_DIR}/private/${DIR}
			fi
		done

		# first branch is writable and remaining are readonly by default.
		${LOG} "[${OWNER}@${URI}] merging local and remote directories"
		mount -t overlayfs -o "lowerdir=${REMOTE_DIR}/private,upperdir=${LOCAL_DIR},workdir=${WORK_DIR}" overlayfs ${MNTPT}
		
		# mounting bind of directories
		for DIR in ${DESKTOP_DIR} ${DOCUMENTS_DIR}; do	
			${LOG} "[${OWNER}@${URI}] enabling write of remote ${DIR} directory"
			mount -o bind ${REMOTE_DIR}/private/${DIR} ${MNTPT}/${DIR}
		done

		# The mountpoint only must be accesible by the user
		if [ -d ${MNTPT} ] && [ ${MNTPT} != "/tmp" ]; then
			${LOG} "[${OWNER}@${URI}] enforcing permissions of mountpoint"
			chmod 0700 ${MNTPT}
			if [ -n "${OWNERUID}" ] && [ -n "${OWNERGID}" ]; then
				chown ${OWNERUID}:${OWNERGID} ${MNTPT}
			fi
		fi

		${LOG} "[${OWNER}@${URI}] Success."

		exit 0
fi

if ! mount -t cifs ${URI} ${MNTPT} -o "${OPTIONS}"; then
	${LOG} "[${OWNER}@${URI}] can't mount resource. Mounting on tmpfs"
	mount -t tmpfs -o size=200M,mode=0777 tmpfs ${MNTPT}
	exit 1
fi

${LOG} "[${OWNER}@${URI}] Success."
