#!/bin/sh

set -e

LOG="logger -t pam_mount"

MNTPT=$1;shift
OWNER=$1;shift
MORRALLA=$*

if [ "$USER" = "$OWNER" ]; then
	${LOG} "User $USER has no permissions to umount resources (See bug LP: #117736)."
	exit 0
fi

#umount /bin/sigaumount  %(MNTPT) %(OWNER)

GROUP=`echo ${MNTPT} | cut -d "/" -f 3` 
${LOG} "[${OWNER}] umounting resources"

if echo $MNTPT | grep -q ull.es; then
	MNTPT=$(echo $MNTPT | sed 's|/home$||')
fi

for DIR in ${MNTPT}/Documentos ${MNTPT}/Escritorio ${MNTPT} /tmp/${OWNER}-remote; do
	if mountpoint -q ${DIR}; then
		umount -lf ${DIR} || ${LOG} "[${OWNER}] WARNING: Couldn't umount ${DIR}"
	fi
done

## Avoid to delete important empty directories
touch /home/.directory /root/.directory || true

#if [ ${GROUP} != "local" ]; then
#	TMPDIR=/tmp/${GROUP}/${OWNER}
#	if [ -d ${TMPDIR} ]; then
#		umount -lf ${TMPDIR}
#		rmdir --parents ${TMPDIR}
#	fi
#fi

rmdir --parents ${MNTPT} --ignore-fail-on-non-empty
${LOG} "[${OWNER}] Success."
