#!/bin/sh

set -e

LOG="logger -t pam_mount"

MNTPT=$1;shift
USER=$1;shift
USERUID=$1;shift
USERGID=$1;shift
MORRALLA=$*

#cifsmount /sbin/sigamount  %(MNTPT) %(USER) %(USERUID) %(USERGID) %(before=\",\" OPTIONS)"

if grep -q "^${USER}:.*:${MNTPT}:.*" /etc/passwd; then
	${LOG} "local user ${USER} exists. Nothing to mount..."
	exit 0
fi

if mount | grep -q "on ${MNTPT}"; then
	${LOG} "mountpoint for ${MNTPT} already mounted. Skipping."
	exit 0
fi

${LOG} "creating mountpoint for user ${USER}..."
mkdir -p ${MNTPT}

FULLPATH=""
for DIR in $(echo $MNTPT | tr "/" " "); do
	FULLPATH="${FULLPATH}/${DIR}"
	if [ -d ${FULLPATH} ] && [ ${FULLPATH} != "/tmp" ]; then
		# FULLPATH must be created by pam_mount
		chown root:root ${FULLPATH}
		chmod 0751 ${FULLPATH}
	fi
done

# The mountpoint only must be accesible by the user
if [ -d ${MNTPT} ] && [ ${MNTPT} != "/tmp" ]; then
	chmod 0700 ${MNTPT}
fi

GROUP=`echo ${MNTPT} | cut -d "/" -f 3` 
${LOG} "mounting ${USER} from ${GROUP} accounts..."

case ${GROUP} in
	${USER})
		mount -t tmpfs -o size=20M,mode=0777 tmpfs ${MNTPT}
		exit $?
		;;
	tmp|temp|temporal)
		## Temporal space for local client accounts
		mount -t tmpfs -o size=200M,mode=0777 tmpfs ${MNTPT}
		exit $?
		;;
	local)
		URI="//server/${USER}"
		;;
	alumnado.ull.es)
		URI="//aluhome.stic.ull.es/${USER}"
		;;
	ull.es)
		URI="//ddv.ccti.ull.es/${USER}"
		;;
	*)
		URI="//${GROUP}.aulas.ull.es/${USER}"
		;;
esac

# Check if FSCache is available in kernel
if egrep -q "CONFIG_(CIFS_)?FSCACHE=y" /boot/config-`uname -r` || lsmod | grep -q fscache; then
	MORRALLA=",fsc${MORRALLA}"
fi

if ! mount -t cifs ${URI} ${MNTPT} -o "user=${USER},_netdev,serverino,sec=ntlmv2${MORRALLA}"; then
	${LOG} "can't mount resource. Mounting on tmpfs..."
	mount -t tmpfs -o size=100M,mode=0777 tmpfs ${MNTPT}
fi
