#!/bin/bash

# description "Adds a firewall rule to allow SSH connections from the network interface when it goes on."
# author "Enrique Hernández Bello <quique@osl.ull.es>"

set -e

cp -a /lib/ufw/user.rules /lib/ufw/user.rules.$(date +%Y%m%d_%H%M%S)

sed "/in_${IFACE}$/d" -i /lib/ufw/user.rules
sed "/-i ${IFACE} /d" -i /lib/ufw/user.rules

/lib/ufw/ufw-init restart
