#!/bin/bash

# description "Remove the firewall rule to allow SSH connections from the network interface when it goes off."
# author "Enrique Hernández Bello <quique@osl.ull.es>"

set -e

cp -a /etc/ufw/user.rules /etc/ufw/user.rules.$(date +%Y%m%d_%H%M%S)

sed "/in_${IFACE}$/d" -i /etc/ufw/user.rules
sed "/-i ${IFACE} /d" -i /etc/ufw/user.rules

/lib/ufw/ufw-init restart
